"""add username to Users model

Revision ID: 0a2fd8c3a115
Revises: 80bb211442c7
Create Date: 2023-05-06 21:37:32.495962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a2fd8c3a115'
down_revision = '80bb211442c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index('slug')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=25), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_index('slug', ['slug'], unique=False)
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
