"""Add post_pic to BlogPost

Revision ID: 658bc83a7e18
Revises: e0971765080c
Create Date: 2023-05-24 00:43:47.769694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658bc83a7e18'
down_revision = 'e0971765080c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_pic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('post_pic')

    # ### end Alembic commands ###
